PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7
Content-Type: application/json

{
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 99
}